version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskmanager_ci_web    # changed name
    ports:
      - "8081:80"                          # changed port to avoid conflict
    volumes:
      - ./app:/var/www/html               # volume mount to sync code changes
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: taskmanager_ci_db     # changed name
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taskdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data_ci:/var/lib/mysql         # changed volume for CI

volumes:
  db_data_ci:

