version: '3.8'

services:
  webapp:
    container_name: slayed-webapp-jenkins  # unique container name
    build: .
    ports:
      - "8080:80"                         # use a different host port (8081 instead of 80)
    volumes:
      - .:/var/www/html
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: taskdb
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
