version: '3.8'

services:
  web:
    container_name: taskmanager_web
    build: .
    ports:
      - "8081:80"  # Expose on 8081
    volumes:
      - ./app:/var/www/html  # Avoid mounting the entire context root
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: taskmanager_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: taskdb
    volumes:
      - db_data:/var/lib/mysql
      - ./app/db-init:/docker-entrypoint-initdb.d

volumes:
  db_data:
